// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: farm_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Awaken.Contracts.Farm {

  #region Events
  public partial class Deposit : aelf::IEvent<Deposit>
  {
    public global::System.Collections.Generic.IEnumerable<Deposit> GetIndexed()
    {
      return new List<Deposit>
      {
      new Deposit
      {
        User = User
      },
      new Deposit
      {
        Pid = Pid
      },
      };
    }

    public Deposit GetNonIndexed()
    {
      return new Deposit
      {
        Amount = Amount,
      };
    }
  }

  public partial class Withdraw : aelf::IEvent<Withdraw>
  {
    public global::System.Collections.Generic.IEnumerable<Withdraw> GetIndexed()
    {
      return new List<Withdraw>
      {
      new Withdraw
      {
        User = User
      },
      new Withdraw
      {
        Pid = Pid
      },
      };
    }

    public Withdraw GetNonIndexed()
    {
      return new Withdraw
      {
        Amount = Amount,
      };
    }
  }

  public partial class ClaimRevenue : aelf::IEvent<ClaimRevenue>
  {
    public global::System.Collections.Generic.IEnumerable<ClaimRevenue> GetIndexed()
    {
      return new List<ClaimRevenue>
      {
      new ClaimRevenue
      {
        User = User
      },
      new ClaimRevenue
      {
        Pid = Pid
      },
      };
    }

    public ClaimRevenue GetNonIndexed()
    {
      return new ClaimRevenue
      {
        Amount = Amount,
        TokenType = TokenType,
      };
    }
  }

  public partial class WeightSet : aelf::IEvent<WeightSet>
  {
    public global::System.Collections.Generic.IEnumerable<WeightSet> GetIndexed()
    {
      return new List<WeightSet>
      {
      };
    }

    public WeightSet GetNonIndexed()
    {
      return new WeightSet
      {
        Pid = Pid,
        NewAllocationPoint = NewAllocationPoint,
      };
    }
  }

  public partial class PoolAdded : aelf::IEvent<PoolAdded>
  {
    public global::System.Collections.Generic.IEnumerable<PoolAdded> GetIndexed()
    {
      return new List<PoolAdded>
      {
      };
    }

    public PoolAdded GetNonIndexed()
    {
      return new PoolAdded
      {
        Token = Token,
        Pid = Pid,
        AllocationPoint = AllocationPoint,
        LastRewardBlockHeight = LastRewardBlockHeight,
        PoolType = PoolType,
      };
    }
  }

  public partial class DistributeTokenPerBlockSet : aelf::IEvent<DistributeTokenPerBlockSet>
  {
    public global::System.Collections.Generic.IEnumerable<DistributeTokenPerBlockSet> GetIndexed()
    {
      return new List<DistributeTokenPerBlockSet>
      {
      };
    }

    public DistributeTokenPerBlockSet GetNonIndexed()
    {
      return new DistributeTokenPerBlockSet
      {
        NewDistributeTokenPerBlock1 = NewDistributeTokenPerBlock1,
        NewDistributeTokenPerBlock2 = NewDistributeTokenPerBlock2,
      };
    }
  }

  public partial class HalvingPeriodSet : aelf::IEvent<HalvingPeriodSet>
  {
    public global::System.Collections.Generic.IEnumerable<HalvingPeriodSet> GetIndexed()
    {
      return new List<HalvingPeriodSet>
      {
      };
    }

    public HalvingPeriodSet GetNonIndexed()
    {
      return new HalvingPeriodSet
      {
        Period1 = Period1,
        Period2 = Period2,
      };
    }
  }

  public partial class NewRewardSet : aelf::IEvent<NewRewardSet>
  {
    public global::System.Collections.Generic.IEnumerable<NewRewardSet> GetIndexed()
    {
      return new List<NewRewardSet>
      {
      };
    }

    public NewRewardSet GetNonIndexed()
    {
      return new NewRewardSet
      {
        StartBlock = StartBlock,
        EndBlock = EndBlock,
        UsdtPerBlock = UsdtPerBlock,
      };
    }
  }

  public partial class UpdatePool : aelf::IEvent<UpdatePool>
  {
    public global::System.Collections.Generic.IEnumerable<UpdatePool> GetIndexed()
    {
      return new List<UpdatePool>
      {
      };
    }

    public UpdatePool GetNonIndexed()
    {
      return new UpdatePool
      {
        Pid = Pid,
        DistributeTokenAmount = DistributeTokenAmount,
        UsdtAmount = UsdtAmount,
        UpdateBlockHeight = UpdateBlockHeight,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class FarmContractContainer
  {
    static readonly string __ServiceName = "FarmContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.SetHalvingPeriodInput> __Marshaller_SetHalvingPeriodInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.SetHalvingPeriodInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.SetDistributeTokenPerBlockInput> __Marshaller_SetDistributeTokenPerBlockInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.SetDistributeTokenPerBlockInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.AddPoolInput> __Marshaller_AddPoolInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.AddPoolInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.SetReDepositInput> __Marshaller_SetReDepositInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.SetReDepositInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.NewRewardInput> __Marshaller_NewRewardInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.NewRewardInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.SetWeightInput> __Marshaller_SetWeightInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.SetWeightInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.DepositInput> __Marshaller_DepositInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.DepositInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.WithdrawInput> __Marshaller_WithdrawInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.WithdrawInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.ReDepositInput> __Marshaller_ReDepositInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.ReDepositInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.DepositLpInput> __Marshaller_DepositLpInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.DepositLpInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.PendingInput> __Marshaller_PendingInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.PendingInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.PendingOutput> __Marshaller_PendingOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.PendingOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.GetReDepositLimitInput> __Marshaller_GetReDepositLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.GetReDepositLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.GetDistributeTokenBlockRewardOutput> __Marshaller_GetDistributeTokenBlockRewardOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.GetDistributeTokenBlockRewardOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.PendingLockDistributeTokenInput> __Marshaller_PendingLockDistributeTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.PendingLockDistributeTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.GetUserInfoInput> __Marshaller_GetUserInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.GetUserInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.UserInfo> __Marshaller_UserInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.UserInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.PoolInfo> __Marshaller_PoolInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.PoolInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Farm.GetRedepositAmountInput> __Marshaller_GetRedepositAmountInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Farm.GetRedepositAmountInput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Awaken.Contracts.Farm.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Awaken.Contracts.Farm.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.SetHalvingPeriodInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetHalvingPeriod = new aelf::Method<global::Awaken.Contracts.Farm.SetHalvingPeriodInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetHalvingPeriod",
        __Marshaller_SetHalvingPeriodInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.SetDistributeTokenPerBlockInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetDistributeTokenPerBlock = new aelf::Method<global::Awaken.Contracts.Farm.SetDistributeTokenPerBlockInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetDistributeTokenPerBlock",
        __Marshaller_SetDistributeTokenPerBlockInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.AddPoolInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddPool = new aelf::Method<global::Awaken.Contracts.Farm.AddPoolInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddPool",
        __Marshaller_AddPoolInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.SetReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetReDeposit = new aelf::Method<global::Awaken.Contracts.Farm.SetReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetReDeposit",
        __Marshaller_SetReDepositInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetTool = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTool",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOwner = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOwner",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.NewRewardInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_NewReward = new aelf::Method<global::Awaken.Contracts.Farm.NewRewardInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "NewReward",
        __Marshaller_NewRewardInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.SetWeightInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetWeight = new aelf::Method<global::Awaken.Contracts.Farm.SetWeightInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetWeight",
        __Marshaller_SetWeightInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.DepositInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Deposit = new aelf::Method<global::Awaken.Contracts.Farm.DepositInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Deposit",
        __Marshaller_DepositInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Withdraw = new aelf::Method<global::Awaken.Contracts.Farm.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Withdraw",
        __Marshaller_WithdrawInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.ReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ReDeposit = new aelf::Method<global::Awaken.Contracts.Farm.ReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ReDeposit",
        __Marshaller_ReDepositInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MassUpdatePools = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "MassUpdatePools",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdatePool = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdatePool",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.Empty> __Method_FixEndBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "FixEndBlock",
        __Marshaller_google_protobuf_BoolValue,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.DepositLpInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DepositLp = new aelf::Method<global::Awaken.Contracts.Farm.DepositLpInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "DepositLp",
        __Marshaller_DepositLpInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.PendingInput, global::Awaken.Contracts.Farm.PendingOutput> __Method_Pending = new aelf::Method<global::Awaken.Contracts.Farm.PendingInput, global::Awaken.Contracts.Farm.PendingOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "Pending",
        __Marshaller_PendingInput,
        __Marshaller_PendingOutput);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.GetReDepositLimitInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetReDepositLimit = new aelf::Method<global::Awaken.Contracts.Farm.GetReDepositLimitInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReDepositLimit",
        __Marshaller_GetReDepositLimitInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Awaken.Contracts.Farm.GetDistributeTokenBlockRewardOutput> __Method_GetDistributeTokenBlockReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Awaken.Contracts.Farm.GetDistributeTokenBlockRewardOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDistributeTokenBlockReward",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_GetDistributeTokenBlockRewardOutput);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.PendingLockDistributeTokenInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_PendingLockDistributeToken = new aelf::Method<global::Awaken.Contracts.Farm.PendingLockDistributeTokenInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "PendingLockDistributeToken",
        __Marshaller_PendingLockDistributeTokenInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetOwner = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOwner",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetStartBlockOfDistributeToken = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetStartBlockOfDistributeToken",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetDistributeTokenPerBlockConcentratedMining = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDistributeTokenPerBlockConcentratedMining",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetDistributeTokenPerBlockContinuousMining = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDistributeTokenPerBlockContinuousMining",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetUsdtPerBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUsdtPerBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetUsdtStartBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUsdtStartBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetUsdtEndBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUsdtEndBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCycle = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCycle",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetHalvingPeriod0 = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHalvingPeriod0",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetHalvingPeriod1 = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHalvingPeriod1",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalReward",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetIssuedReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetIssuedReward",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetEndBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetEndBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.GetUserInfoInput, global::Awaken.Contracts.Farm.UserInfo> __Method_GetUserInfo = new aelf::Method<global::Awaken.Contracts.Farm.GetUserInfoInput, global::Awaken.Contracts.Farm.UserInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUserInfo",
        __Marshaller_GetUserInfoInput,
        __Marshaller_UserInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Awaken.Contracts.Farm.PoolInfo> __Method_GetPoolInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Awaken.Contracts.Farm.PoolInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPoolInfo",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_PoolInfo);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalAllocPoint = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalAllocPoint",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPoolLength = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPoolLength",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.Farm.GetRedepositAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetRedepositAmount = new aelf::Method<global::Awaken.Contracts.Farm.GetRedepositAmountInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRedepositAmount",
        __Marshaller_GetRedepositAmountInput,
        __Marshaller_google_protobuf_Int64Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Awaken.Contracts.Farm.FarmContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Awaken.Contracts.Farm.FarmContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

