// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pool_two_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Awaken.Contracts.PoolTwoContract {

  #region Events
  public partial class Deposit : aelf::IEvent<Deposit>
  {
    public global::System.Collections.Generic.IEnumerable<Deposit> GetIndexed()
    {
      return new List<Deposit>
      {
      new Deposit
      {
        User = User
      },
      new Deposit
      {
        Pid = Pid
      },
      };
    }

    public Deposit GetNonIndexed()
    {
      return new Deposit
      {
        Amount = Amount,
      };
    }
  }

  public partial class Withdraw : aelf::IEvent<Withdraw>
  {
    public global::System.Collections.Generic.IEnumerable<Withdraw> GetIndexed()
    {
      return new List<Withdraw>
      {
      new Withdraw
      {
        User = User
      },
      new Withdraw
      {
        Pid = Pid
      },
      };
    }

    public Withdraw GetNonIndexed()
    {
      return new Withdraw
      {
        Amount = Amount,
      };
    }
  }

  public partial class ClaimRevenue : aelf::IEvent<ClaimRevenue>
  {
    public global::System.Collections.Generic.IEnumerable<ClaimRevenue> GetIndexed()
    {
      return new List<ClaimRevenue>
      {
      };
    }

    public ClaimRevenue GetNonIndexed()
    {
      return new ClaimRevenue
      {
        User = User,
        Pid = Pid,
        TokenSymbol = TokenSymbol,
        TokenType = TokenType,
        Amount = Amount,
      };
    }
  }

  public partial class WeightSet : aelf::IEvent<WeightSet>
  {
    public global::System.Collections.Generic.IEnumerable<WeightSet> GetIndexed()
    {
      return new List<WeightSet>
      {
      };
    }

    public WeightSet GetNonIndexed()
    {
      return new WeightSet
      {
        Pid = Pid,
        NewAllocationPoint = NewAllocationPoint,
      };
    }
  }

  public partial class PoolAdded : aelf::IEvent<PoolAdded>
  {
    public global::System.Collections.Generic.IEnumerable<PoolAdded> GetIndexed()
    {
      return new List<PoolAdded>
      {
      };
    }

    public PoolAdded GetNonIndexed()
    {
      return new PoolAdded
      {
        Token = Token,
        Pid = Pid,
        AllocationPoint = AllocationPoint,
        LastRewardBlockHeight = LastRewardBlockHeight,
        PoolType = PoolType,
      };
    }
  }

  public partial class DistributeTokenPerBlockSet : aelf::IEvent<DistributeTokenPerBlockSet>
  {
    public global::System.Collections.Generic.IEnumerable<DistributeTokenPerBlockSet> GetIndexed()
    {
      return new List<DistributeTokenPerBlockSet>
      {
      };
    }

    public DistributeTokenPerBlockSet GetNonIndexed()
    {
      return new DistributeTokenPerBlockSet
      {
        NewDistributeTokenPerBlock = NewDistributeTokenPerBlock,
      };
    }
  }

  public partial class HalvingPeriodSet : aelf::IEvent<HalvingPeriodSet>
  {
    public global::System.Collections.Generic.IEnumerable<HalvingPeriodSet> GetIndexed()
    {
      return new List<HalvingPeriodSet>
      {
      };
    }

    public HalvingPeriodSet GetNonIndexed()
    {
      return new HalvingPeriodSet
      {
        Period = Period,
      };
    }
  }

  public partial class UpdatePool : aelf::IEvent<UpdatePool>
  {
    public global::System.Collections.Generic.IEnumerable<UpdatePool> GetIndexed()
    {
      return new List<UpdatePool>
      {
      };
    }

    public UpdatePool GetNonIndexed()
    {
      return new UpdatePool
      {
        Pid = Pid,
        DistributeTokenAmount = DistributeTokenAmount,
        UpdateBlockHeight = UpdateBlockHeight,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class PoolTwoContractContainer
  {
    static readonly string __ServiceName = "PoolTwoContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.AddInput> __Marshaller_AddInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.AddInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.SetInput> __Marshaller_SetInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.SetInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.ReDepositInput> __Marshaller_ReDepositInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.ReDepositInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.DepositInput> __Marshaller_DepositInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.DepositInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.WithdrawInput> __Marshaller_WithdrawInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.WithdrawInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.SetLpTokenAddressInput> __Marshaller_SetLpTokenAddressInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.SetLpTokenAddressInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.BigIntValue> __Marshaller_aelf_BigIntValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.BigIntValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.PendingInput> __Marshaller_PendingInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.PendingInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.UserInfoInput> __Marshaller_UserInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.UserInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.UserInfoStruct> __Marshaller_UserInfoStruct = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.UserInfoStruct.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.PoolTwoContract.PoolInfoStruct> __Marshaller_PoolInfoStruct = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.PoolTwoContract.PoolInfoStruct.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetHalvingPeriod = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetHalvingPeriod",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetFarmPoolOne = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetFarmPoolOne",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetDistributeTokenPerBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetDistributeTokenPerBlock",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.AddInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Add = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.AddInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Add",
        __Marshaller_AddInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.SetInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Set = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.SetInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Set",
        __Marshaller_SetInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MassUpdatePools = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "MassUpdatePools",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdatePool = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "UpdatePool",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.ReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ReDeposit = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.ReDepositInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ReDeposit",
        __Marshaller_ReDepositInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.DepositInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Deposit = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.DepositInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Deposit",
        __Marshaller_DepositInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Withdraw = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.WithdrawInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Withdraw",
        __Marshaller_WithdrawInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.Empty> __Method_FixEndBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "FixEndBlock",
        __Marshaller_google_protobuf_BoolValue,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.SetLpTokenAddressInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetLpTokenAddress = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.SetLpTokenAddressInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetLpTokenAddress",
        __Marshaller_SetLpTokenAddressInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOwner = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOwner",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_PoolLength = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "PoolLength",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_Phase = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "Phase",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Types.BigIntValue> __Method_Reward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "Reward",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Types.BigIntValue> __Method_GetDistributeTokenBlockReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDistributeTokenBlockReward",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.PendingInput, global::AElf.Types.BigIntValue> __Method_Pending = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.PendingInput, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "Pending",
        __Marshaller_PendingInput,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Awaken.Contracts.PoolTwoContract.UserInfoInput, global::Awaken.Contracts.PoolTwoContract.UserInfoStruct> __Method_UserInfo = new aelf::Method<global::Awaken.Contracts.PoolTwoContract.UserInfoInput, global::Awaken.Contracts.PoolTwoContract.UserInfoStruct>(
        aelf::MethodType.View,
        __ServiceName,
        "UserInfo",
        __Marshaller_UserInfoInput,
        __Marshaller_UserInfoStruct);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_StartBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "StartBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_DistributeToken = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "DistributeToken",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Awaken.Contracts.PoolTwoContract.PoolInfoStruct> __Method_PoolInfo = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Awaken.Contracts.PoolTwoContract.PoolInfoStruct>(
        aelf::MethodType.View,
        __ServiceName,
        "PoolInfo",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_PoolInfoStruct);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_TotalAllocPoint = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "TotalAllocPoint",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_HalvingPeriod = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "HalvingPeriod",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_FarmPoolOne = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "FarmPoolOne",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue> __Method_TotalReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "TotalReward",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue> __Method_IssuedReward = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IssuedReward",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_EndBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "EndBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue> __Method_DistributeTokenPerBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "DistributeTokenPerBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_RedepositAdjustFlag = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "RedepositAdjustFlag",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_RedepositStartBlock = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "RedepositStartBlock",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Awaken.Contracts.PoolTwoContract.PoolTwoContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Awaken.Contracts.PoolTwoContract.PoolTwoContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

  }
}
#endregion

