// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: a_token_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Awaken.Contracts.AToken {

  #region Events
  public partial class AccrueInterest : aelf::IEvent<AccrueInterest>
  {
    public global::System.Collections.Generic.IEnumerable<AccrueInterest> GetIndexed()
    {
      return new List<AccrueInterest>
      {
      };
    }

    public AccrueInterest GetNonIndexed()
    {
      return new AccrueInterest
      {
        AToken = AToken,
        Cash = Cash,
        InterestAccumulated = InterestAccumulated,
        BorrowIndex = BorrowIndex,
        TotalBorrows = TotalBorrows,
        BorrowRatePerBlock = BorrowRatePerBlock,
        SupplyRatePerBlock = SupplyRatePerBlock,
      };
    }
  }

  public partial class Mint : aelf::IEvent<Mint>
  {
    public global::System.Collections.Generic.IEnumerable<Mint> GetIndexed()
    {
      return new List<Mint>
      {
      };
    }

    public Mint GetNonIndexed()
    {
      return new Mint
      {
        Underlying = Underlying,
        AToken = AToken,
        UnderlyingAmount = UnderlyingAmount,
        ATokenAmount = ATokenAmount,
        Sender = Sender,
        Channel = Channel,
      };
    }
  }

  public partial class Redeem : aelf::IEvent<Redeem>
  {
    public global::System.Collections.Generic.IEnumerable<Redeem> GetIndexed()
    {
      return new List<Redeem>
      {
      };
    }

    public Redeem GetNonIndexed()
    {
      return new Redeem
      {
        Underlying = Underlying,
        AToken = AToken,
        UnderlyingAmount = UnderlyingAmount,
        ATokenAmount = ATokenAmount,
        Sender = Sender,
      };
    }
  }

  public partial class Borrow : aelf::IEvent<Borrow>
  {
    public global::System.Collections.Generic.IEnumerable<Borrow> GetIndexed()
    {
      return new List<Borrow>
      {
      };
    }

    public Borrow GetNonIndexed()
    {
      return new Borrow
      {
        AToken = AToken,
        Borrower = Borrower,
        Amount = Amount,
        BorrowBalance = BorrowBalance,
        TotalBorrows = TotalBorrows,
      };
    }
  }

  public partial class RepayBorrow : aelf::IEvent<RepayBorrow>
  {
    public global::System.Collections.Generic.IEnumerable<RepayBorrow> GetIndexed()
    {
      return new List<RepayBorrow>
      {
      };
    }

    public RepayBorrow GetNonIndexed()
    {
      return new RepayBorrow
      {
        AToken = AToken,
        Payer = Payer,
        Borrower = Borrower,
        Amount = Amount,
        BorrowBalance = BorrowBalance,
        TotalBorrows = TotalBorrows,
      };
    }
  }

  public partial class LiquidateBorrow : aelf::IEvent<LiquidateBorrow>
  {
    public global::System.Collections.Generic.IEnumerable<LiquidateBorrow> GetIndexed()
    {
      return new List<LiquidateBorrow>
      {
      };
    }

    public LiquidateBorrow GetNonIndexed()
    {
      return new LiquidateBorrow
      {
        RepayAToken = RepayAToken,
        Liquidator = Liquidator,
        Borrower = Borrower,
        RepayAmount = RepayAmount,
        SeizeAToken = SeizeAToken,
        SeizeTokenAmount = SeizeTokenAmount,
      };
    }
  }

  public partial class AdminChanged : aelf::IEvent<AdminChanged>
  {
    public global::System.Collections.Generic.IEnumerable<AdminChanged> GetIndexed()
    {
      return new List<AdminChanged>
      {
      };
    }

    public AdminChanged GetNonIndexed()
    {
      return new AdminChanged
      {
        OldAdmin = OldAdmin,
        NewAdmin = NewAdmin,
      };
    }
  }

  public partial class ReserveFactorChanged : aelf::IEvent<ReserveFactorChanged>
  {
    public global::System.Collections.Generic.IEnumerable<ReserveFactorChanged> GetIndexed()
    {
      return new List<ReserveFactorChanged>
      {
      };
    }

    public ReserveFactorChanged GetNonIndexed()
    {
      return new ReserveFactorChanged
      {
        OldReserveFactor = OldReserveFactor,
        NewReserveFactor = NewReserveFactor,
        AToken = AToken,
      };
    }
  }

  public partial class ReservesAdded : aelf::IEvent<ReservesAdded>
  {
    public global::System.Collections.Generic.IEnumerable<ReservesAdded> GetIndexed()
    {
      return new List<ReservesAdded>
      {
      };
    }

    public ReservesAdded GetNonIndexed()
    {
      return new ReservesAdded
      {
        Underlying = Underlying,
        AToken = AToken,
        AddAmount = AddAmount,
        TotalReserves = TotalReserves,
        Sender = Sender,
      };
    }
  }

  public partial class ReservesReduced : aelf::IEvent<ReservesReduced>
  {
    public global::System.Collections.Generic.IEnumerable<ReservesReduced> GetIndexed()
    {
      return new List<ReservesReduced>
      {
      };
    }

    public ReservesReduced GetNonIndexed()
    {
      return new ReservesReduced
      {
        Underlying = Underlying,
        AToken = AToken,
        ReduceAmount = ReduceAmount,
        TotalReserves = TotalReserves,
        Sender = Sender,
      };
    }
  }

  public partial class Transferred : aelf::IEvent<Transferred>
  {
    public global::System.Collections.Generic.IEnumerable<Transferred> GetIndexed()
    {
      return new List<Transferred>
      {
      new Transferred
      {
        From = From
      },
      new Transferred
      {
        To = To
      },
      new Transferred
      {
        Symbol = Symbol
      },
      };
    }

    public Transferred GetNonIndexed()
    {
      return new Transferred
      {
        Amount = Amount,
        Memo = Memo,
      };
    }
  }

  public partial class Approved : aelf::IEvent<Approved>
  {
    public global::System.Collections.Generic.IEnumerable<Approved> GetIndexed()
    {
      return new List<Approved>
      {
      new Approved
      {
        Owner = Owner
      },
      new Approved
      {
        Spender = Spender
      },
      new Approved
      {
        Symbol = Symbol
      },
      };
    }

    public Approved GetNonIndexed()
    {
      return new Approved
      {
        Amount = Amount,
      };
    }
  }

  public partial class UnApproved : aelf::IEvent<UnApproved>
  {
    public global::System.Collections.Generic.IEnumerable<UnApproved> GetIndexed()
    {
      return new List<UnApproved>
      {
      new UnApproved
      {
        Owner = Owner
      },
      new UnApproved
      {
        Spender = Spender
      },
      new UnApproved
      {
        Symbol = Symbol
      },
      };
    }

    public UnApproved GetNonIndexed()
    {
      return new UnApproved
      {
        Amount = Amount,
      };
    }
  }

  public partial class TokenCreated : aelf::IEvent<TokenCreated>
  {
    public global::System.Collections.Generic.IEnumerable<TokenCreated> GetIndexed()
    {
      return new List<TokenCreated>
      {
      };
    }

    public TokenCreated GetNonIndexed()
    {
      return new TokenCreated
      {
        Symbol = Symbol,
        TokenName = TokenName,
        Decimals = Decimals,
        AToken = AToken,
        Underlying = Underlying,
        TokenContract = TokenContract,
        Controller = Controller,
      };
    }
  }

  #endregion
  public static partial class ATokenContractContainer
  {
    static readonly string __ServiceName = "ATokenContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.CreateInput> __Marshaller_CreateInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.CreateInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.MintInput> __Marshaller_MintInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.MintInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.RedeemInput> __Marshaller_RedeemInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.RedeemInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.RedeemUnderlyingInput> __Marshaller_RedeemUnderlyingInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.RedeemUnderlyingInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.BorrowInput> __Marshaller_BorrowInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.BorrowInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.RepayBorrowInput> __Marshaller_RepayBorrowInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.RepayBorrowInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.RepayBorrowBehalfInput> __Marshaller_RepayBorrowBehalfInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.RepayBorrowBehalfInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.LiquidateBorrowInput> __Marshaller_LiquidateBorrowInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.LiquidateBorrowInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.AddReservesInput> __Marshaller_AddReservesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.AddReservesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.ReduceReservesInput> __Marshaller_ReduceReservesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.ReduceReservesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.SeizeInput> __Marshaller_SeizeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.SeizeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.TransferInput> __Marshaller_TransferInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.TransferInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.TransferFromInput> __Marshaller_TransferFromInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.TransferFromInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.ApproveInput> __Marshaller_ApproveInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.ApproveInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.SetReserveFactorInput> __Marshaller_SetReserveFactorInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.SetReserveFactorInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.SetInterestRateModelInput> __Marshaller_SetInterestRateModelInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.SetInterestRateModelInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.Account> __Marshaller_Account = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.Account.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.GetAccountSnapshotOutput> __Marshaller_GetAccountSnapshotOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.GetAccountSnapshotOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.GetBalancesInput> __Marshaller_GetBalancesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.GetBalancesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.Balances> __Marshaller_Balances = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.Balances.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.AToken.GetAllowanceInput> __Marshaller_GetAllowanceInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.AToken.GetAllowanceInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Awaken.Contracts.AToken.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Awaken.Contracts.AToken.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Create = new aelf::Method<global::Awaken.Contracts.AToken.CreateInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Create",
        __Marshaller_CreateInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.MintInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Mint = new aelf::Method<global::Awaken.Contracts.AToken.MintInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Mint",
        __Marshaller_MintInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.RedeemInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Redeem = new aelf::Method<global::Awaken.Contracts.AToken.RedeemInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Redeem",
        __Marshaller_RedeemInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.RedeemUnderlyingInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RedeemUnderlying = new aelf::Method<global::Awaken.Contracts.AToken.RedeemUnderlyingInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RedeemUnderlying",
        __Marshaller_RedeemUnderlyingInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.BorrowInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Borrow = new aelf::Method<global::Awaken.Contracts.AToken.BorrowInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Borrow",
        __Marshaller_BorrowInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.RepayBorrowInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RepayBorrow = new aelf::Method<global::Awaken.Contracts.AToken.RepayBorrowInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RepayBorrow",
        __Marshaller_RepayBorrowInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.RepayBorrowBehalfInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RepayBorrowBehalf = new aelf::Method<global::Awaken.Contracts.AToken.RepayBorrowBehalfInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RepayBorrowBehalf",
        __Marshaller_RepayBorrowBehalfInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.LiquidateBorrowInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_LiquidateBorrow = new aelf::Method<global::Awaken.Contracts.AToken.LiquidateBorrowInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "LiquidateBorrow",
        __Marshaller_LiquidateBorrowInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.AddReservesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddReserves = new aelf::Method<global::Awaken.Contracts.AToken.AddReservesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddReserves",
        __Marshaller_AddReservesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.ReduceReservesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ReduceReserves = new aelf::Method<global::Awaken.Contracts.AToken.ReduceReservesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ReduceReserves",
        __Marshaller_ReduceReservesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AccrueInterest = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AccrueInterest",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.SeizeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Seize = new aelf::Method<global::Awaken.Contracts.AToken.SeizeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Seize",
        __Marshaller_SeizeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.TransferInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Transfer = new aelf::Method<global::Awaken.Contracts.AToken.TransferInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Transfer",
        __Marshaller_TransferInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.TransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferFrom = new aelf::Method<global::Awaken.Contracts.AToken.TransferFromInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferFrom",
        __Marshaller_TransferFromInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Approve = new aelf::Method<global::Awaken.Contracts.AToken.ApproveInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Approve",
        __Marshaller_ApproveInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetComptroller = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetComptroller",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.SetReserveFactorInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetReserveFactor = new aelf::Method<global::Awaken.Contracts.AToken.SetReserveFactorInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetReserveFactor",
        __Marshaller_SetReserveFactorInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.SetInterestRateModelInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetInterestRateModel = new aelf::Method<global::Awaken.Contracts.AToken.SetInterestRateModelInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetInterestRateModel",
        __Marshaller_SetInterestRateModelInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetUnderlyingBalance = new aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUnderlyingBalance",
        __Marshaller_Account,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.Account, global::Awaken.Contracts.AToken.GetAccountSnapshotOutput> __Method_GetAccountSnapshot = new aelf::Method<global::Awaken.Contracts.AToken.Account, global::Awaken.Contracts.AToken.GetAccountSnapshotOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAccountSnapshot",
        __Marshaller_Account,
        __Marshaller_GetAccountSnapshotOutput);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetBorrowRatePerBlock = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBorrowRatePerBlock",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetSupplyRatePerBlock = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSupplyRatePerBlock",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalBorrows = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalBorrows",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCurrentBorrowBalance = new aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.Action,
        __ServiceName,
        "GetCurrentBorrowBalance",
        __Marshaller_Account,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetBorrowBalanceStored = new aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBorrowBalanceStored",
        __Marshaller_Account,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCurrentExchangeRate = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.Action,
        __ServiceName,
        "GetCurrentExchangeRate",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetExchangeRateStored = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetExchangeRateStored",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCash = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCash",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetReserveFactor = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReserveFactor",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetComptroller = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetComptroller",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::AElf.Types.Address> __Method_GetInterestRateModel = new aelf::Method<global::AElf.Types.Address, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetInterestRateModel",
        __Marshaller_aelf_Address,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetInitialExchangeRate = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetInitialExchangeRate",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalReserves = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalReserves",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetAccrualBlockNumber = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAccrualBlockNumber",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetBorrowIndex = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBorrowIndex",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_GetATokenAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetATokenAddress",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.StringValue> __Method_GetUnderlying = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.StringValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUnderlying",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_StringValue);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetBalance = new aelf::Method<global::Awaken.Contracts.AToken.Account, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBalance",
        __Marshaller_Account,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.GetBalancesInput, global::Awaken.Contracts.AToken.Balances> __Method_GetBalances = new aelf::Method<global::Awaken.Contracts.AToken.GetBalancesInput, global::Awaken.Contracts.AToken.Balances>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBalances",
        __Marshaller_GetBalancesInput,
        __Marshaller_Balances);

    static readonly aelf::Method<global::Awaken.Contracts.AToken.GetAllowanceInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetAllowance = new aelf::Method<global::Awaken.Contracts.AToken.GetAllowanceInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAllowance",
        __Marshaller_GetAllowanceInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetTotalSupply = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTotalSupply",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetDecimals = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDecimals",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Awaken.Contracts.AToken.ATokenContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Awaken.Contracts.AToken.ATokenContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of ATokenContract</summary>
  }
}
#endregion

