// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: controller_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Awaken.Contracts.Controller {

  #region Events
  public partial class MarketListed : aelf::IEvent<MarketListed>
  {
    public global::System.Collections.Generic.IEnumerable<MarketListed> GetIndexed()
    {
      return new List<MarketListed>
      {
      };
    }

    public MarketListed GetNonIndexed()
    {
      return new MarketListed
      {
        AToken = AToken,
      };
    }
  }

  public partial class MarketEntered : aelf::IEvent<MarketEntered>
  {
    public global::System.Collections.Generic.IEnumerable<MarketEntered> GetIndexed()
    {
      return new List<MarketEntered>
      {
      };
    }

    public MarketEntered GetNonIndexed()
    {
      return new MarketEntered
      {
        AToken = AToken,
        Account = Account,
      };
    }
  }

  public partial class MarketExited : aelf::IEvent<MarketExited>
  {
    public global::System.Collections.Generic.IEnumerable<MarketExited> GetIndexed()
    {
      return new List<MarketExited>
      {
      };
    }

    public MarketExited GetNonIndexed()
    {
      return new MarketExited
      {
        AToken = AToken,
        Account = Account,
      };
    }
  }

  public partial class CloseFactorChanged : aelf::IEvent<CloseFactorChanged>
  {
    public global::System.Collections.Generic.IEnumerable<CloseFactorChanged> GetIndexed()
    {
      return new List<CloseFactorChanged>
      {
      };
    }

    public CloseFactorChanged GetNonIndexed()
    {
      return new CloseFactorChanged
      {
        OldCloseFactor = OldCloseFactor,
        NewCloseFactor = NewCloseFactor,
      };
    }
  }

  public partial class CollateralFactorChanged : aelf::IEvent<CollateralFactorChanged>
  {
    public global::System.Collections.Generic.IEnumerable<CollateralFactorChanged> GetIndexed()
    {
      return new List<CollateralFactorChanged>
      {
      };
    }

    public CollateralFactorChanged GetNonIndexed()
    {
      return new CollateralFactorChanged
      {
        AToken = AToken,
        OldCollateralFactor = OldCollateralFactor,
        NewCollateralFactor = NewCollateralFactor,
      };
    }
  }

  public partial class LiquidationIncentiveChanged : aelf::IEvent<LiquidationIncentiveChanged>
  {
    public global::System.Collections.Generic.IEnumerable<LiquidationIncentiveChanged> GetIndexed()
    {
      return new List<LiquidationIncentiveChanged>
      {
      };
    }

    public LiquidationIncentiveChanged GetNonIndexed()
    {
      return new LiquidationIncentiveChanged
      {
        OldLiquidationIncentive = OldLiquidationIncentive,
        NewLiquidationIncentive = NewLiquidationIncentive,
      };
    }
  }

  public partial class MaxAssetsChanged : aelf::IEvent<MaxAssetsChanged>
  {
    public global::System.Collections.Generic.IEnumerable<MaxAssetsChanged> GetIndexed()
    {
      return new List<MaxAssetsChanged>
      {
      };
    }

    public MaxAssetsChanged GetNonIndexed()
    {
      return new MaxAssetsChanged
      {
        OldMaxAssets = OldMaxAssets,
        NewMaxAssets = NewMaxAssets,
      };
    }
  }

  public partial class PriceOracleChanged : aelf::IEvent<PriceOracleChanged>
  {
    public global::System.Collections.Generic.IEnumerable<PriceOracleChanged> GetIndexed()
    {
      return new List<PriceOracleChanged>
      {
      };
    }

    public PriceOracleChanged GetNonIndexed()
    {
      return new PriceOracleChanged
      {
        OldPriceOracle = OldPriceOracle,
        NewPriceOracle = NewPriceOracle,
      };
    }
  }

  public partial class PauseGuardianChanged : aelf::IEvent<PauseGuardianChanged>
  {
    public global::System.Collections.Generic.IEnumerable<PauseGuardianChanged> GetIndexed()
    {
      return new List<PauseGuardianChanged>
      {
      };
    }

    public PauseGuardianChanged GetNonIndexed()
    {
      return new PauseGuardianChanged
      {
        OldPauseGuardian = OldPauseGuardian,
        NewPauseGuardian = NewPauseGuardian,
      };
    }
  }

  public partial class ActionPaused : aelf::IEvent<ActionPaused>
  {
    public global::System.Collections.Generic.IEnumerable<ActionPaused> GetIndexed()
    {
      return new List<ActionPaused>
      {
      };
    }

    public ActionPaused GetNonIndexed()
    {
      return new ActionPaused
      {
        AToken = AToken,
        Action = Action,
        PauseState = PauseState,
      };
    }
  }

  public partial class MarketPlatformTokened : aelf::IEvent<MarketPlatformTokened>
  {
    public global::System.Collections.Generic.IEnumerable<MarketPlatformTokened> GetIndexed()
    {
      return new List<MarketPlatformTokened>
      {
      };
    }

    public MarketPlatformTokened GetNonIndexed()
    {
      return new MarketPlatformTokened
      {
        AToken = AToken,
        IsPlatformTokened = IsPlatformTokened,
      };
    }
  }

  public partial class PlatformTokenRateChanged : aelf::IEvent<PlatformTokenRateChanged>
  {
    public global::System.Collections.Generic.IEnumerable<PlatformTokenRateChanged> GetIndexed()
    {
      return new List<PlatformTokenRateChanged>
      {
      };
    }

    public PlatformTokenRateChanged GetNonIndexed()
    {
      return new PlatformTokenRateChanged
      {
        OldPlatformTokenRate = OldPlatformTokenRate,
        NewPlatformTokenRate = NewPlatformTokenRate,
      };
    }
  }

  public partial class PlatformTokenSpeedUpdated : aelf::IEvent<PlatformTokenSpeedUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<PlatformTokenSpeedUpdated> GetIndexed()
    {
      return new List<PlatformTokenSpeedUpdated>
      {
      };
    }

    public PlatformTokenSpeedUpdated GetNonIndexed()
    {
      return new PlatformTokenSpeedUpdated
      {
        AToken = AToken,
        NewSpeed = NewSpeed,
      };
    }
  }

  public partial class DistributedSupplierPlatformToken : aelf::IEvent<DistributedSupplierPlatformToken>
  {
    public global::System.Collections.Generic.IEnumerable<DistributedSupplierPlatformToken> GetIndexed()
    {
      return new List<DistributedSupplierPlatformToken>
      {
      };
    }

    public DistributedSupplierPlatformToken GetNonIndexed()
    {
      return new DistributedSupplierPlatformToken
      {
        AToken = AToken,
        Supplier = Supplier,
        PlatformTokenDelta = PlatformTokenDelta,
        PlatformTokenSupplyIndex = PlatformTokenSupplyIndex,
      };
    }
  }

  public partial class DistributedBorrowerPlatformToken : aelf::IEvent<DistributedBorrowerPlatformToken>
  {
    public global::System.Collections.Generic.IEnumerable<DistributedBorrowerPlatformToken> GetIndexed()
    {
      return new List<DistributedBorrowerPlatformToken>
      {
      };
    }

    public DistributedBorrowerPlatformToken GetNonIndexed()
    {
      return new DistributedBorrowerPlatformToken
      {
        AToken = AToken,
        Borrower = Borrower,
        PlatformTokenDelta = PlatformTokenDelta,
        PlatformTokenBorrowIndex = PlatformTokenBorrowIndex,
      };
    }
  }

  public partial class BorrowCapChanged : aelf::IEvent<BorrowCapChanged>
  {
    public global::System.Collections.Generic.IEnumerable<BorrowCapChanged> GetIndexed()
    {
      return new List<BorrowCapChanged>
      {
      };
    }

    public BorrowCapChanged GetNonIndexed()
    {
      return new BorrowCapChanged
      {
        AToken = AToken,
        NewBorrowCap = NewBorrowCap,
      };
    }
  }

  public partial class BorrowCapGuardianChanged : aelf::IEvent<BorrowCapGuardianChanged>
  {
    public global::System.Collections.Generic.IEnumerable<BorrowCapGuardianChanged> GetIndexed()
    {
      return new List<BorrowCapGuardianChanged>
      {
      };
    }

    public BorrowCapGuardianChanged GetNonIndexed()
    {
      return new BorrowCapGuardianChanged
      {
        OldBorrowCapGuardian = OldBorrowCapGuardian,
        NewBorrowCapGuardian = NewBorrowCapGuardian,
      };
    }
  }

  #endregion
  public static partial class ControllerContractContainer
  {
    static readonly string __ServiceName = "ControllerContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.ATokens> __Marshaller_ATokens = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.ATokens.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.MintAllowedInput> __Marshaller_MintAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.MintAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.MintVerifyInput> __Marshaller_MintVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.MintVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.RedeemAllowedInput> __Marshaller_RedeemAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.RedeemAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.RedeemVerifyInput> __Marshaller_RedeemVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.RedeemVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.BorrowAllowedInput> __Marshaller_BorrowAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.BorrowAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.BorrowVerifyInput> __Marshaller_BorrowVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.BorrowVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.RepayBorrowAllowedInput> __Marshaller_RepayBorrowAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.RepayBorrowAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.RepayBorrowVerifyInput> __Marshaller_RepayBorrowVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.RepayBorrowVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.LiquidateBorrowAllowedInput> __Marshaller_LiquidateBorrowAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.LiquidateBorrowAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.LiquidateBorrowVerifyInput> __Marshaller_LiquidateBorrowVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.LiquidateBorrowVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.SeizeAllowedInput> __Marshaller_SeizeAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.SeizeAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.SeizeVerifyInput> __Marshaller_SeizeVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.SeizeVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.TransferAllowedInput> __Marshaller_TransferAllowedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.TransferAllowedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.TransferVerifyInput> __Marshaller_TransferVerifyInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.TransferVerifyInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.LiquidateCalculateSeizeTokensInput> __Marshaller_LiquidateCalculateSeizeTokensInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.LiquidateCalculateSeizeTokensInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.SetCollateralFactorInput> __Marshaller_SetCollateralFactorInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.SetCollateralFactorInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.SetMarketBorrowCapsInput> __Marshaller_SetMarketBorrowCapsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.SetMarketBorrowCapsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.SetPausedInput> __Marshaller_SetPausedInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.SetPausedInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.ClaimPlatformTokenInput> __Marshaller_ClaimPlatformTokenInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.ClaimPlatformTokenInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.AssetList> __Marshaller_AssetList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.AssetList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.Account> __Marshaller_Account = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.Account.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityInput> __Marshaller_GetHypotheticalAccountLiquidityInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityOutput> __Marshaller_GetHypotheticalAccountLiquidityOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.Market> __Marshaller_Market = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.Market.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.GetAccountLiquidityOutput> __Marshaller_GetAccountLiquidityOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.GetAccountLiquidityOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Controller.PlatformTokenMarketState> __Marshaller_PlatformTokenMarketState = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Controller.PlatformTokenMarketState.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.BigIntValue> __Marshaller_aelf_BigIntValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.BigIntValue.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Awaken.Contracts.Controller.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Awaken.Contracts.Controller.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.ATokens, global::Google.Protobuf.WellKnownTypes.Empty> __Method_EnterMarkets = new aelf::Method<global::Awaken.Contracts.Controller.ATokens, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "EnterMarkets",
        __Marshaller_ATokens,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ExitMarket = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ExitMarket",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.MintAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MintAllowed = new aelf::Method<global::Awaken.Contracts.Controller.MintAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "MintAllowed",
        __Marshaller_MintAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.MintVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MintVerify = new aelf::Method<global::Awaken.Contracts.Controller.MintVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "MintVerify",
        __Marshaller_MintVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.RedeemAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RedeemAllowed = new aelf::Method<global::Awaken.Contracts.Controller.RedeemAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RedeemAllowed",
        __Marshaller_RedeemAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.RedeemVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RedeemVerify = new aelf::Method<global::Awaken.Contracts.Controller.RedeemVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RedeemVerify",
        __Marshaller_RedeemVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.BorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BorrowAllowed = new aelf::Method<global::Awaken.Contracts.Controller.BorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BorrowAllowed",
        __Marshaller_BorrowAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.BorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BorrowVerify = new aelf::Method<global::Awaken.Contracts.Controller.BorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BorrowVerify",
        __Marshaller_BorrowVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.RepayBorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RepayBorrowAllowed = new aelf::Method<global::Awaken.Contracts.Controller.RepayBorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RepayBorrowAllowed",
        __Marshaller_RepayBorrowAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.RepayBorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RepayBorrowVerify = new aelf::Method<global::Awaken.Contracts.Controller.RepayBorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RepayBorrowVerify",
        __Marshaller_RepayBorrowVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.LiquidateBorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_LiquidateBorrowAllowed = new aelf::Method<global::Awaken.Contracts.Controller.LiquidateBorrowAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "LiquidateBorrowAllowed",
        __Marshaller_LiquidateBorrowAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.LiquidateBorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_LiquidateBorrowVerify = new aelf::Method<global::Awaken.Contracts.Controller.LiquidateBorrowVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "LiquidateBorrowVerify",
        __Marshaller_LiquidateBorrowVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SeizeAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SeizeAllowed = new aelf::Method<global::Awaken.Contracts.Controller.SeizeAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SeizeAllowed",
        __Marshaller_SeizeAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SeizeVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SeizeVerify = new aelf::Method<global::Awaken.Contracts.Controller.SeizeVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SeizeVerify",
        __Marshaller_SeizeVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.TransferAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferAllowed = new aelf::Method<global::Awaken.Contracts.Controller.TransferAllowedInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferAllowed",
        __Marshaller_TransferAllowedInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.TransferVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferVerify = new aelf::Method<global::Awaken.Contracts.Controller.TransferVerifyInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferVerify",
        __Marshaller_TransferVerifyInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.LiquidateCalculateSeizeTokensInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_LiquidateCalculateSeizeTokens = new aelf::Method<global::Awaken.Contracts.Controller.LiquidateCalculateSeizeTokensInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.Action,
        __ServiceName,
        "LiquidateCalculateSeizeTokens",
        __Marshaller_LiquidateCalculateSeizeTokensInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCloseFactor = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCloseFactor",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SetCollateralFactorInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetCollateralFactor = new aelf::Method<global::Awaken.Contracts.Controller.SetCollateralFactorInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetCollateralFactor",
        __Marshaller_SetCollateralFactorInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxAssets = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxAssets",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetLiquidationIncentive = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetLiquidationIncentive",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SupportMarket = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SupportMarket",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SetMarketBorrowCapsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMarketBorrowCaps = new aelf::Method<global::Awaken.Contracts.Controller.SetMarketBorrowCapsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMarketBorrowCaps",
        __Marshaller_SetMarketBorrowCapsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetBorrowCapGuardian = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetBorrowCapGuardian",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPauseGuardian = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPauseGuardian",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SetPausedInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_SetMintPaused = new aelf::Method<global::Awaken.Contracts.Controller.SetPausedInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMintPaused",
        __Marshaller_SetPausedInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.SetPausedInput, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_SetBorrowPaused = new aelf::Method<global::Awaken.Contracts.Controller.SetPausedInput, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetBorrowPaused",
        __Marshaller_SetPausedInput,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_SetTransferPaused = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetTransferPaused",
        __Marshaller_google_protobuf_BoolValue,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_SetSeizePaused = new aelf::Method<global::Google.Protobuf.WellKnownTypes.BoolValue, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSeizePaused",
        __Marshaller_google_protobuf_BoolValue,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPriceOracle = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPriceOracle",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RefreshPlatformTokenSpeeds = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RefreshPlatformTokenSpeeds",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.ClaimPlatformTokenInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ClaimPlatformToken = new aelf::Method<global::Awaken.Contracts.Controller.ClaimPlatformTokenInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ClaimPlatformToken",
        __Marshaller_ClaimPlatformTokenInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPlatformTokenRate = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPlatformTokenRate",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.ATokens, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddPlatformTokenMarkets = new aelf::Method<global::Awaken.Contracts.Controller.ATokens, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddPlatformTokenMarkets",
        __Marshaller_ATokens,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DropPlatformTokenMarket = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "DropPlatformTokenMarket",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.AssetList> __Method_GetAssetsIn = new aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.AssetList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAssetsIn",
        __Marshaller_aelf_Address,
        __Marshaller_AssetList);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.Account, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_CheckMembership = new aelf::Method<global::Awaken.Contracts.Controller.Account, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "CheckMembership",
        __Marshaller_Account,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Awaken.Contracts.Controller.ATokens> __Method_GetAllMarkets = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Awaken.Contracts.Controller.ATokens>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAllMarkets",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_ATokens);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPendingAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPendingAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCloseFactor = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCloseFactor",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetCollateralFactor = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCollateralFactor",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxAssets = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMaxAssets",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetLiquidationIncentive = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLiquidationIncentive",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetMarketBorrowCaps = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMarketBorrowCaps",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetBorrowCapGuardian = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBorrowCapGuardian",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityInput, global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityOutput> __Method_GetHypotheticalAccountLiquidity = new aelf::Method<global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityInput, global::Awaken.Contracts.Controller.GetHypotheticalAccountLiquidityOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetHypotheticalAccountLiquidity",
        __Marshaller_GetHypotheticalAccountLiquidityInput,
        __Marshaller_GetHypotheticalAccountLiquidityOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPriceOracle = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPriceOracle",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.Market> __Method_GetMarket = new aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.Market>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMarket",
        __Marshaller_aelf_Address,
        __Marshaller_Market);

    static readonly aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.GetAccountLiquidityOutput> __Method_GetAccountLiquidity = new aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.GetAccountLiquidityOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAccountLiquidity",
        __Marshaller_aelf_Address,
        __Marshaller_GetAccountLiquidityOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPlatformTokenRate = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenRate",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPlatformTokenSpeeds = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenSpeeds",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.PlatformTokenMarketState> __Method_GetPlatformTokenSupplyState = new aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.PlatformTokenMarketState>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenSupplyState",
        __Marshaller_aelf_Address,
        __Marshaller_PlatformTokenMarketState);

    static readonly aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.PlatformTokenMarketState> __Method_GetPlatformTokenBorrowState = new aelf::Method<global::AElf.Types.Address, global::Awaken.Contracts.Controller.PlatformTokenMarketState>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenBorrowState",
        __Marshaller_aelf_Address,
        __Marshaller_PlatformTokenMarketState);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.Account, global::AElf.Types.BigIntValue> __Method_GetPlatformTokenSupplierIndex = new aelf::Method<global::Awaken.Contracts.Controller.Account, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenSupplierIndex",
        __Marshaller_Account,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.Account, global::AElf.Types.BigIntValue> __Method_GetPlatformTokenBorrowerIndex = new aelf::Method<global::Awaken.Contracts.Controller.Account, global::AElf.Types.BigIntValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenBorrowerIndex",
        __Marshaller_Account,
        __Marshaller_aelf_BigIntValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPlatformTokenAccrued = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenAccrued",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetPauseGuardian = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPauseGuardian",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetTransferGuardianPaused = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetTransferGuardianPaused",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetSeizeGuardianPaused = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetSeizeGuardianPaused",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetMintGuardianPaused = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMintGuardianPaused",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_GetBorrowGuardianPaused = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBorrowGuardianPaused",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPlatformTokenClaimThreshold = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenClaimThreshold",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.Controller.ClaimPlatformTokenInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPlatformTokenClaimAmount = new aelf::Method<global::Awaken.Contracts.Controller.ClaimPlatformTokenInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlatformTokenClaimAmount",
        __Marshaller_ClaimPlatformTokenInput,
        __Marshaller_google_protobuf_Int64Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Awaken.Contracts.Controller.ControllerContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Awaken.Contracts.Controller.ControllerContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

  }
}
#endregion

