// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Awaken_shadowfax_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Awaken.Contracts.Shadowfax {

  #region Events
  public partial class AddPublicOffering : aelf::IEvent<AddPublicOffering>
  {
    public global::System.Collections.Generic.IEnumerable<AddPublicOffering> GetIndexed()
    {
      return new List<AddPublicOffering>
      {
      };
    }

    public AddPublicOffering GetNonIndexed()
    {
      return new AddPublicOffering
      {
        OfferingTokenSymbol = OfferingTokenSymbol,
        OfferingTokenAmount = OfferingTokenAmount,
        WantTokenSymbol = WantTokenSymbol,
        WantTokenAmount = WantTokenAmount,
        Publisher = Publisher,
        StartTime = StartTime,
        EndTime = EndTime,
        PublicId = PublicId,
      };
    }
  }

  public partial class ChangeAscription : aelf::IEvent<ChangeAscription>
  {
    public global::System.Collections.Generic.IEnumerable<ChangeAscription> GetIndexed()
    {
      return new List<ChangeAscription>
      {
      };
    }

    public ChangeAscription GetNonIndexed()
    {
      return new ChangeAscription
      {
        TokenSymbol = TokenSymbol,
        OldPublisher = OldPublisher,
        NewPublisher = NewPublisher,
      };
    }
  }

  public partial class Withdraw : aelf::IEvent<Withdraw>
  {
    public global::System.Collections.Generic.IEnumerable<Withdraw> GetIndexed()
    {
      return new List<Withdraw>
      {
      };
    }

    public Withdraw GetNonIndexed()
    {
      return new Withdraw
      {
        PubilicId = PubilicId,
        To = To,
        WantToken = WantToken,
        OfferingToken = OfferingToken,
      };
    }
  }

  public partial class Invest : aelf::IEvent<Invest>
  {
    public global::System.Collections.Generic.IEnumerable<Invest> GetIndexed()
    {
      return new List<Invest>
      {
      };
    }

    public Invest GetNonIndexed()
    {
      return new Invest
      {
        PublicId = PublicId,
        Investor = Investor,
        TokenSymbol = TokenSymbol,
        Income = Income,
        Spend = Spend,
        Channel = Channel,
      };
    }
  }

  public partial class Harvest : aelf::IEvent<Harvest>
  {
    public global::System.Collections.Generic.IEnumerable<Harvest> GetIndexed()
    {
      return new List<Harvest>
      {
      };
    }

    public Harvest GetNonIndexed()
    {
      return new Harvest
      {
        PublicId = PublicId,
        To = To,
        Amount = Amount,
      };
    }
  }

  #endregion
  public static partial class ShadowfaxContractContainer
  {
    static readonly string __ServiceName = "ShadowfaxContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.AddPublicOfferingInput> __Marshaller_AddPublicOfferingInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.AddPublicOfferingInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.ChangeAscriptionInput> __Marshaller_ChangeAscriptionInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.ChangeAscriptionInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.InvestInput> __Marshaller_InvestInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.InvestInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.ResetTimeSpanInput> __Marshaller_ResetTimeSpanInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.ResetTimeSpanInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.PublicOfferingOutput> __Marshaller_PublicOfferingOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.PublicOfferingOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.UserInfoInput> __Marshaller_UserInfoInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.UserInfoInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Awaken.Contracts.Shadowfax.UserInfoStruct> __Marshaller_UserInfoStruct = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Awaken.Contracts.Shadowfax.UserInfoStruct.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.StringValue.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Awaken.Contracts.Shadowfax.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.AddPublicOfferingInput, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_AddPublicOffering = new aelf::Method<global::Awaken.Contracts.Shadowfax.AddPublicOfferingInput, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddPublicOffering",
        __Marshaller_AddPublicOfferingInput,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.ChangeAscriptionInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeAscription = new aelf::Method<global::Awaken.Contracts.Shadowfax.ChangeAscriptionInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeAscription",
        __Marshaller_ChangeAscriptionInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Withdraw = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Withdraw",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.InvestInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Invest = new aelf::Method<global::Awaken.Contracts.Shadowfax.InvestInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Invest",
        __Marshaller_InvestInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Harvest = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Harvest",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.ResetTimeSpanInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ResetTimeSpan = new aelf::Method<global::Awaken.Contracts.Shadowfax.ResetTimeSpanInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ResetTimeSpan",
        __Marshaller_ResetTimeSpanInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_Owner = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "Owner",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_MaximalTimeSpan = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "MaximalTimeSpan",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_MinimalTimespan = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "MinimalTimespan",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Awaken.Contracts.Shadowfax.PublicOfferingOutput> __Method_PublicOfferings = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Awaken.Contracts.Shadowfax.PublicOfferingOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "PublicOfferings",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_PublicOfferingOutput);

    static readonly aelf::Method<global::Awaken.Contracts.Shadowfax.UserInfoInput, global::Awaken.Contracts.Shadowfax.UserInfoStruct> __Method_UserInfo = new aelf::Method<global::Awaken.Contracts.Shadowfax.UserInfoInput, global::Awaken.Contracts.Shadowfax.UserInfoStruct>(
        aelf::MethodType.View,
        __ServiceName,
        "UserInfo",
        __Marshaller_UserInfoInput,
        __Marshaller_UserInfoStruct);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetPublicOfferingLength = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPublicOfferingLength",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address> __Method_Ascription = new aelf::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "Ascription",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_aelf_Address);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Awaken.Contracts.Shadowfax.AwakenShadowfaxContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::Awaken.Contracts.Shadowfax.AwakenShadowfaxContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion
  }
}
#endregion

